flags: {}

packages:
- shared
- node

resolver: lts-5.9

extra-deps:
  - applicative-extras-0.1.8
  - ctrie-0.1.0.3
  - sockaddr-0.0.0
  - cacophony-0.7.0
  - cryptonite-0.17
  - unagi-chan-0.4.0.0
  - base58-bytestring-0.1.0

extra-include-dirs:
- /usr/local/include
extra-lib-dirs:
- /usr/local/lib
