flags: {}

packages:
- yaks/parsec-layout
- yaks/easytest
- shared
- node

compiler-check: match-exact
resolver: lts-7.10
compiler: ghc-8.0.1.20161117
setup-info:
  ghc:
    linux64:
      8.0.1.20161117:
        url: https://downloads.haskell.org/~ghc/8.0.2-rc1/ghc-8.0.1.20161117-x86_64-deb8-linux.tar.xz
        content-length: 112047972
        sha1: 6a6e4c9c53c71cc84b6966a9f61948542fd2f15a
    macosx:
      8.0.1.20161117:
        url: https://downloads.haskell.org/~ghc/8.0.2-rc1/ghc-8.0.1.20161117-x86_64-apple-darwin.tar.xz
        content-length: 113379688
        sha1: 53ed03d986a49ea680c291540ce44ce469514d7c
    windows64:
      8.0.1.20161117:
        url: https://downloads.haskell.org/~ghc/8.0.2-rc1/ghc-8.0.1.20161117-x86_64-unknown-mingw32.tar.xz
        content-length: 155652048
        sha1: 74118dd8fd8b5e4c69b25df1644273fbe13177c7

extra-deps:
  - applicative-extras-0.1.8
  - ctrie-0.1.0.3
  - sockaddr-0.0.0
  - cacophony-0.7.0
  - cryptonite-0.17
  - unagi-chan-0.4.0.0
  - base58-bytestring-0.1.0

extra-include-dirs:
- /usr/local/include
extra-lib-dirs:
- /usr/local/lib
