flags: {}

allow-newer: true # async package has needlessly strict upper bound

allow-different-user: true

packages:
- yaks/easytest
- parser-typechecker

#compiler-check: match-exact
resolver: lts-12.5

extra-deps:
- base58-bytestring-0.1.0
- strings-1.1
- relation-0.2.1

ghc-options:
 # All packages
 "$locals": -Werror #-freverse-errors
